version: '3.8'

services:
  db:
    image: mysql:8.0.32
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quote_tier
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - symfony

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db_data:

networks:
  symfony:
    driver: bridge
