app_controllers:
    resource: '../src/Http/Controller/'
    type: attribute
    name_prefix: 'app.'

api_controllers:
    resource: '../src/Http/Api/Controller/'
    type: attribute
    name_prefix: 'api.'